import type { Metadata } from "next";

import "./globals.css";
import Provider from "@/components/Provider";
import TopNav from "@/components/nav/TopNav";
import SideMenu from "@/components/SideMenu";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html suppressHydrationWarning  lang="en" className="h-full">
      <body className="flex flex-col bg-stone-200 dark:bg-default-50 h-full">
        <Provider>
            <TopNav />
          <div className='flex grow overflow-auto'>
              <aside className='basis-1/6 shrink-0 border-r border-neutral-500 pt-20 sticky top-0 px-6'>
                <SideMenu />
              </aside>
              <main className='flex-1 pt-20 h-full'>
                  {children}
              </main>
              <aside className='basis-1/4 shrink-0 px-6 pt-20 bg-stone-300 dark:bg-default-100 sticky top-0'>
                  <div className='flex flex-col gap-6'>
                      Gelicek
                  </div>
                  
              </aside>
          </div>
        </Provider>
      </body>
    </html>
  );
}
